
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HacForo.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ForumThread
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ForumThread()
    {

        this.Comments = new HashSet<Comment>();

    }


    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public System.DateTime CreationDate { get; set; }

    public int UserId { get; set; }

    public string ImageLink { get; set; }

    public int Points { get; set; }



    public virtual User User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comment> Comments { get; set; }

}

}
